language: java
jdk:
  - oraclejdk8
dist: trusty
addons:
  sonarcloud:
    organization: "dumaya"
    #token:
    #  secure: "8f9fb7e73d2155442190eca2ab5b6321ecc1be39" # encrypted value of your token

services:
  - postgresql

before_script:
  - psql -c 'create database myerp;' -U postgres
  - psql -c "create user adm_myerp with password 'myerp';" -U postgres
  - psql -f 'dump.sql' -U postgres
  - psql -c 'grant all privileges on database myerp to adm_myerp;' -U postgres
  - psql -c 'GRANT USAGE ON SCHEMA myerp TO adm_myerp;'
  - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA myerp to adm_myerp;'
  - psql -c 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA myerp TO adm_myerp;'

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=8f9fb7e73d2155442190eca2ab5b6321ecc1be39 -Dsonar.projectKey=dumaya_OCComptaTestP9 -P test-business